name: Deploy Frontend
 
on:
  push:
    branch: 
      - release
jobs:
  name: Upload to Amazon S3
  runs-on: ubuntu-latest
# These permissions are needed to interact with GitHub's OIDC Token endpoint.
  permissions:
    id-token: write
    contents: read

  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: setup nodejs
    uses: actions/setup-node@v3
    with:
      node-version: 16
  
  - name: install and build source
    run : |-
      npm install
      npm run build
    working-directory: frontend

  - name: Configure AWS credentials from Production account
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-southeast-1

  - name: Copy files to the production website with the AWS CLI
    run: |
      aws s3 rm s3://test.hcmute.me --recursive
      aws s3 sync . s3://test.hcmute.me
    working-directory: frontend/build

